CoworkTesting/CoworkTesting/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('user_app.urls', namespace='user_app'))
]

CoworkTesting/user_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^login/$',
        'django.contrib.auth.views.login',
        name='login',
        kwargs={'template_name': 'user_app/login.html'}
    ),
    url(
        r'^logout/$',
        'django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': '/'}
    ),
    url(r'^$', views.index, name='index'),
]

CoworkTesting/user_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Hub(models.Model):
    name = models.CharField(max_length=30)
    location = models.CharField(max_length=30)

    def __str__(self):
        return '%s | %s' % (self.name, self.location)


class CoworkUser(models.Model):
    user = models.OneToOneField(User)
    hubs = models.ManyToManyField(Hub)

    class Meta:
        permissions = (
            ("view_coworkuser", "Can view cowork user"),
            # ("change_user", "Can change user's details"),
            # ("add_user", "Can add new user"),
            # ("delete_user", "Can delete user")
        )

CoworkTesting/user_app/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import get_user_model


# @login_required(login_url='login/')
def index(request):
    users = []
    if request.user.is_authenticated():
        users = get_user_model().objects.all()
    context = {'users': users, 'username': request.user.username or None}
    return render(request, 'user_app/index.html', context)

CoworkTesting/templates/user_app/base.html
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Cowork Test App</title>

        <!-- Bootstrap CSS -->
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style type="text/css">
            .allow {
                color:#4CAF50;
            }
            .not-allow , .errors{
                color: #F44336;
            }
            a , a:hover{
                text-decoration: none;
            }
        </style>
    </head>
    <body>
        <div class="center-block">
            <a href="/"><h1 class="text-center">Welcome to Cowork Test App</h1>
            </a>
        </div>

        {% block content %}
        {% endblock %}

        <!-- jQuery -->
        <script src="//code.jquery.com/jquery.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </body>
</html>

CoworkTesting/templates/user_app/index.html
{% extends "user_app/base.html" %}

{% load has_permission_filter %}

{% block content%}

<div class="row">
    <div class="col-xs-10">
        <div class="pull-right">
            {% if user.is_authenticated %}
                <p>Welcome, {{ user.username }}  <a href="{% url 'user_app:logout' %}">[logout]</a></p>
                <p>Hub:
                {% for hub in user.coworkuser.hubs.all %}
                    {{ hub.location }}
                {% endfor %}
                </p>
            {% else %}
                <p>Welcome, Guest <a href="{% url 'user_app:login' %}">[login]</a></p>
            {% endif %}
        </div>
    </div>
</div>

<div class="center-block">
    <div class="col-xs-6 col-xs-offset-3">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead class="thead-inverse">
                    <tr>
                        <th>#</th>
                        <th>Username</th>
                        <th>Location</th>
                        <th>Permission for User Model</th>
                    </tr>
                </thead>
                <tbody>
                    {% for u in users %}
                    <tr>
                        <td scope="row">{{ u.id }}</td>
                        <td>{{ u.username }}</td>
                        <td>
                        {% for hub in u.coworkuser.hubs.all %}
                            {{ hub.location }}
                        {% endfor %}
                        </td>
                        <td class="allow">
                            <span class={% has_location_perm user 'user_app.view_coworkuser' u %}>
                                View
                            </span>
                            |
                             <span class={% has_location_perm user 'user_app.add_coworkuser' u %}>
                                Add
                            </span>
                            |
                             <span class={% has_location_perm user 'user_app.edit_coworkuser' u %}>
                                Update
                            </span>
                            |
                             <span class={% has_location_perm user 'user_app.delete_coworkuser' u %}>
                                Delete
                            </span>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

CoworkTesting/templates/user_app/login.html
{% extends "user_app/base.html" %}

{% block content%}

<div class="row">
    <div class="col-xs-4 col-xs-offset-4">
        {% if form.errors %}
        <p class="errors">Your username and password didn't match. Please try again.</p>
        {% endif %}
        <form action="{% url 'user_app:login' %}" method="POST" role="form">
            {% csrf_token %}
            <legend>Login</legend>
            <table>
            {{ form }}
            </table>
            <input type="submit" value="login" />
            <input type="hidden" name="next" value="/" />

    <!--
           <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="" placeholder="Enter your username">
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="" placeholder="Enter your password">
            </div>

            <button type="submit" class="btn btn-primary">Login</button> -->
        </form>
    </div>
</div>

{% endblock %}